### PR TITLE
Added support for Fly 2

### PR DESCRIPTION
**Pull request by hzlmn**
Hi, `Fly` reached new major version `v2` (currently under beta tag) , so this will be out-dated.

cc @lukeed

### CODE REVIEW

**Comment by hzlmn** [comment]
Oops, seems like `Travis` file should be updated, as we move away from old `Node`

**Comment by lukeed** [comment]
@hzlmn I'd go ahead & add an updated `.travis.yml` as part of this. 

Other changes:

* there's also no need to assign `self`
* you can assign constants
* the `error` within `this.emit('plugin_error')` needs to be a string; so use `error.message`

**Comment by hzlmn** [comment]
@lukeed Is it alive? Even if `Fly` allow to use just `postcss` directly, it is nice to have plugin.

**Comment by lukeed** [comment]
@hzlmn Not sure. I've waited 10 days to get `fly-uglify` updated.

If you're just looking to use the `autoprefixer` plugin, I have [fly-autoprefixer](https://github.com/lukeed/fly-autoprefixer).

**Comment by hzlmn** [comment]
@ai Could you please provide access to @lukeed , so this plugin can be updated?

**Comment by ai** [comment]
@morishitter are you agree to make a @lukeed maintainer?

**Comment by morishitter** [comment]
@ai sure. @lukeed thanks :)

**Comment by lukeed** [comment]
@ai @morishitter @hzlmn 👍 Thanks guys

**Comment by jbucaran** [comment]
@lukeed Thanks!

**Comment by lukeed** [comment]
I'm actually still not at a level to merge this & move forward. Just FYI

**Comment by tjbenton** [comment]
Can this be merged so it can be used without having to have install https://github.com/hzlmn/fly-postcss/tree/v2

**Comment by lukeed** [comment]
Totally forgot about this one, 😅 

@hzlmn Can you make 2 more changes for me?

1. Rewrite the export function itself to use the `fly` parameter. This is more future-proof because eventually `this` will no longer be bound on the definition.

  ```js
  module.exports = function (fly) {
    fly.plugin('postcss', {}, function * (file, opts) {
    })
  }
  ```

2. Remove the `object-assign` dependency & just use native `Object.assign` instead.

Thanks

**Comment by hzlmn** [comment]
@lukeed Done

**Comment by lukeed** [comment]
Thanks @hzlmn ! Looks like the last thing is updating `.travis.yml` to be `6` and `7` only. 😆

**Comment by hzlmn** [comment]
@lukeed Oh sure, updated

**Comment by lukeed** [comment]
Hello?

**Pull request closed without merging**
